sudo: false

language: python

python:
  - "2.7"

services:
  - docker

install: "pip install lain-cli"

script:
  - lain config save-global private_docker_registry 'registry.lain.local'
  - lain build
  - lain test
  - LAIN_APPNAME=webrouter
  - LAIN_IMAGE_VERSION="$(git show -s --format=%ct $TRAVIS_COMMIT)-$TRAVIS_COMMIT"
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env --name webrouter-build $LAIN_APPNAME:build-$LAIN_IMAGE_VERSION bash -c 'rm -rf * && yum install -y git && git clone https://github.com/laincloud/webrouter && cd webrouter && pip install codecov && pip install -r pip-req.txt && mkdir -p /var/log/watcher && make test-cov && bash <(curl -s https://codecov.io/bash) && codecov'


after_success:
  - LAIN_APPNAME=webrouter
  - LAIN_IMAGE_VERSION="$(git show -s --format=%ct $TRAVIS_COMMIT)-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker tag $LAIN_APPNAME:release-$LAIN_IMAGE_VERSION laincloud/$LAIN_APPNAME:release-$LAIN_IMAGE_VERSION;
    docker tag $LAIN_APPNAME:meta-$LAIN_IMAGE_VERSION laincloud/$LAIN_APPNAME:meta-$LAIN_IMAGE_VERSION;
    docker push laincloud/$LAIN_APPNAME:release-$LAIN_IMAGE_VERSION;
    docker push laincloud/$LAIN_APPNAME:meta-$LAIN_IMAGE_VERSION;
    fi
